[package]
name = "isere"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freertos-rust = "0.1.2"
heapless = "0.7.16"
log = "0.4.20"
rquickjs = "0.3.1"

[build-dependencies]
freertos-cargo-build = "*"

[toolchain]
channel = "nightly"
