// Raw FFI bindings to QuickJS C API.
//
// These are manually written to match the QuickJS API surface used by isere.
// In a production build, these could be auto-generated by bindgen.
//
// QuickJS is compiled as a Zephyr C library (see c_libs/CMakeLists.txt)
// and linked into the final binary.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use core::ffi::{c_char, c_int, c_void};

// Opaque types
pub enum JSRuntime {}
pub enum JSContext {}

// JSValue is a tagged union in QuickJS. On 32-bit ARM it's typically 8 bytes.
// The exact layout depends on QuickJS configuration. We use a repr(C) struct
// matching the QuickJS NaN-boxing representation.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct JSValue {
    pub u: JSValueUnion,
    pub tag: i32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union JSValueUnion {
    pub int32: i32,
    pub float64: f64,
    pub ptr: *mut c_void,
}

// JS value tags
pub const JS_TAG_INT: i32 = 0;
pub const JS_TAG_BOOL: i32 = 1;
pub const JS_TAG_NULL: i32 = 2;
pub const JS_TAG_UNDEFINED: i32 = 3;
pub const JS_TAG_EXCEPTION: i32 = 6;
pub const JS_TAG_FLOAT64: i32 = 7;
pub const JS_TAG_OBJECT: i32 = -1;
pub const JS_TAG_STRING: i32 = -7;

// JS eval flags
pub const JS_EVAL_TYPE_GLOBAL: c_int = 0;
pub const JS_EVAL_TYPE_MODULE: c_int = 1;
pub const JS_EVAL_FLAG_COMPILE_ONLY: c_int = 1 << 5;

// JS property flags
pub const JS_GPN_STRING_MASK: c_int = 1 << 0;
pub const JS_GPN_ENUM_ONLY: c_int = 1 << 4;

// Malloc functions struct for custom allocator
#[repr(C)]
pub struct JSMallocFunctions {
    pub js_malloc: Option<unsafe extern "C" fn(s: *mut JSMallocState, size: usize) -> *mut c_void>,
    pub js_free: Option<unsafe extern "C" fn(s: *mut JSMallocState, ptr: *mut c_void)>,
    pub js_realloc:
        Option<unsafe extern "C" fn(s: *mut JSMallocState, ptr: *mut c_void, size: usize) -> *mut c_void>,
    pub js_malloc_usable_size: Option<unsafe extern "C" fn(ptr: *const c_void) -> usize>,
}

#[repr(C)]
pub struct JSMallocState {
    pub malloc_count: usize,
    pub malloc_size: usize,
    pub malloc_limit: usize,
    pub opaque: *mut c_void,
}

#[repr(C)]
pub struct JSPropertyEnum {
    pub is_enumerable: c_int,
    pub atom: u32, // JSAtom
}

// C function type for JS callbacks
pub type JSCFunction =
    unsafe extern "C" fn(ctx: *mut JSContext, this_val: JSValue, argc: c_int, argv: *const JSValue) -> JSValue;

extern "C" {
    // Runtime lifecycle
    pub fn JS_NewRuntime() -> *mut JSRuntime;
    pub fn JS_NewRuntime2(
        mf: *const JSMallocFunctions,
        opaque: *mut c_void,
    ) -> *mut JSRuntime;
    pub fn JS_FreeRuntime(rt: *mut JSRuntime);
    pub fn JS_SetMemoryLimit(rt: *mut JSRuntime, limit: usize);
    pub fn JS_SetMaxStackSize(rt: *mut JSRuntime, stack_size: usize);
    pub fn JS_GetRuntime(ctx: *mut JSContext) -> *mut JSRuntime;

    // Context lifecycle
    pub fn JS_NewContext(rt: *mut JSRuntime) -> *mut JSContext;
    pub fn JS_NewContextRaw(rt: *mut JSRuntime) -> *mut JSContext;
    pub fn JS_FreeContext(ctx: *mut JSContext);
    pub fn JS_SetContextOpaque(ctx: *mut JSContext, opaque: *mut c_void);
    pub fn JS_GetContextOpaque(ctx: *mut JSContext) -> *mut c_void;

    // Intrinsics
    pub fn JS_AddIntrinsicBaseObjects(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicDate(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicEval(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicJSON(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicPromise(ctx: *mut JSContext);

    // Global object
    pub fn JS_GetGlobalObject(ctx: *mut JSContext) -> JSValue;

    // Value creation
    pub fn JS_NewObject(ctx: *mut JSContext) -> JSValue;
    pub fn JS_NewString(ctx: *mut JSContext, str: *const c_char) -> JSValue;
    pub fn JS_NewInt32(ctx: *mut JSContext, val: i32) -> JSValue;
    pub fn JS_NewBool(ctx: *mut JSContext, val: c_int) -> JSValue;
    pub fn JS_NewCFunction(
        ctx: *mut JSContext,
        func: JSCFunction,
        name: *const c_char,
        length: c_int,
    ) -> JSValue;

    // Property access
    pub fn JS_SetPropertyStr(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: *const c_char,
        val: JSValue,
    ) -> c_int;
    pub fn JS_GetPropertyStr(ctx: *mut JSContext, this_obj: JSValue, prop: *const c_char) -> JSValue;
    pub fn JS_GetProperty(ctx: *mut JSContext, this_obj: JSValue, prop: u32) -> JSValue;

    // Value inspection
    pub fn JS_ToInt32(ctx: *mut JSContext, pres: *mut i32, val: JSValue) -> c_int;
    pub fn JS_ToCStringLen(
        ctx: *mut JSContext,
        plen: *mut usize,
        val: JSValue,
    ) -> *const c_char;
    pub fn JS_FreeCString(ctx: *mut JSContext, ptr: *const c_char);

    // Value type checking helpers
    pub fn JS_IsNumber(v: JSValue) -> c_int;
    pub fn JS_IsString(v: JSValue) -> c_int;
    pub fn JS_IsObject(v: JSValue) -> c_int;
    pub fn JS_IsException(v: JSValue) -> c_int;

    // Memory management
    pub fn JS_FreeValue(ctx: *mut JSContext, v: JSValue);

    // Evaluation
    pub fn JS_Eval(
        ctx: *mut JSContext,
        input: *const c_char,
        input_len: usize,
        filename: *const c_char,
        eval_flags: c_int,
    ) -> JSValue;

    // JSON
    pub fn JS_ParseJSON(
        ctx: *mut JSContext,
        buf: *const c_char,
        buf_len: usize,
        filename: *const c_char,
    ) -> JSValue;
    pub fn JS_JSONStringify(
        ctx: *mut JSContext,
        obj: JSValue,
        replacer: JSValue,
        space: JSValue,
    ) -> JSValue;

    // Property enumeration
    pub fn JS_GetOwnPropertyNames(
        ctx: *mut JSContext,
        ptab: *mut *mut JSPropertyEnum,
        plen: *mut u32,
        obj: JSValue,
        flags: c_int,
    ) -> c_int;
    pub fn JS_AtomToCString(ctx: *mut JSContext, atom: u32) -> *const c_char;
    pub fn JS_FreeAtom(ctx: *mut JSContext, atom: u32);

    // Job execution (promises, async)
    pub fn JS_ExecutePendingJob(rt: *mut JSRuntime, pctx: *mut *mut JSContext) -> c_int;

    // Module support
    pub fn js_module_set_import_meta(
        ctx: *mut JSContext,
        func_val: JSValue,
        use_realpath: c_int,
        is_main: c_int,
    );
}

// Helper constants matching QuickJS
impl JSValue {
    pub const UNDEFINED: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_UNDEFINED,
    };

    pub const NULL: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_NULL,
    };

    pub const FALSE: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_BOOL,
    };

    pub const TRUE: Self = Self {
        u: JSValueUnion { int32: 1 },
        tag: JS_TAG_BOOL,
    };

    pub fn is_exception(&self) -> bool {
        self.tag == JS_TAG_EXCEPTION
    }

    pub fn is_object(&self) -> bool {
        self.tag == JS_TAG_OBJECT
    }

    pub fn is_string(&self) -> bool {
        self.tag == JS_TAG_STRING
    }

    pub fn is_number(&self) -> bool {
        self.tag == JS_TAG_INT || self.tag == JS_TAG_FLOAT64
    }
}
