// Raw FFI bindings to QuickJS C API.
//
// These are manually written to match the QuickJS API surface used by isere.
// In a production build, these could be auto-generated by bindgen.
//
// QuickJS is compiled as a Zephyr C library (see c_libs/CMakeLists.txt)
// and linked into the final binary.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use core::ffi::{c_char, c_int, c_void};

// Opaque types
pub enum JSRuntime {}
pub enum JSContext {}

// JSValue representation depends on the platform:
//
// - 32-bit (RP2350): JS_NAN_BOXING is enabled. JSValue = uint64_t.
//   Tag is in the upper 32 bits, value/pointer in the lower 32 bits.
//   Layout: (tag << 32) | value
//
// - 64-bit (native_sim): JSValue = struct { JSValueUnion u; int64_t tag; }
//   A 16-byte struct with union + tag.
//
// We use conditional compilation to match the target platform.

// JS value tags (same on both layouts)
pub const JS_TAG_INT: i32 = 0;
pub const JS_TAG_BOOL: i32 = 1;
pub const JS_TAG_NULL: i32 = 2;
pub const JS_TAG_UNDEFINED: i32 = 3;
pub const JS_TAG_EXCEPTION: i32 = 6;
pub const JS_TAG_FLOAT64: i32 = 8;
pub const JS_TAG_OBJECT: i32 = -1;
pub const JS_TAG_STRING: i32 = -7;

// --- 32-bit targets: NaN-boxed JSValue = u64 ---
#[cfg(target_pointer_width = "32")]
#[derive(Clone, Copy)]
#[repr(transparent)]
pub struct JSValue(pub u64);

#[cfg(target_pointer_width = "32")]
impl JSValue {
    pub const UNDEFINED: Self = Self::from_tag_val(JS_TAG_UNDEFINED, 0);
    pub const NULL: Self = Self::from_tag_val(JS_TAG_NULL, 0);
    pub const FALSE: Self = Self::from_tag_val(JS_TAG_BOOL, 0);
    pub const TRUE: Self = Self::from_tag_val(JS_TAG_BOOL, 1);

    const fn from_tag_val(tag: i32, val: i32) -> Self {
        Self(((tag as u32 as u64) << 32) | (val as u32 as u64))
    }

    pub fn tag(&self) -> i32 {
        (self.0 >> 32) as i32
    }

    pub fn is_exception(&self) -> bool { self.tag() == JS_TAG_EXCEPTION }
    pub fn is_object(&self) -> bool { self.tag() == JS_TAG_OBJECT }
    pub fn is_string(&self) -> bool { self.tag() == JS_TAG_STRING }
    pub fn is_number(&self) -> bool {
        let tag = self.tag();
        tag == JS_TAG_INT || tag == JS_TAG_FLOAT64
    }
}

// --- 64-bit targets: struct { JSValueUnion u; int64_t tag; } ---
#[cfg(target_pointer_width = "64")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct JSValue {
    pub u: JSValueUnion,
    pub tag: i64,
}

#[cfg(target_pointer_width = "64")]
#[repr(C)]
#[derive(Clone, Copy)]
pub union JSValueUnion {
    pub int32: i32,
    pub float64: f64,
    pub ptr: *mut c_void,
}

#[cfg(target_pointer_width = "64")]
impl JSValue {
    pub const UNDEFINED: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_UNDEFINED as i64,
    };
    pub const NULL: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_NULL as i64,
    };
    pub const FALSE: Self = Self {
        u: JSValueUnion { int32: 0 },
        tag: JS_TAG_BOOL as i64,
    };
    pub const TRUE: Self = Self {
        u: JSValueUnion { int32: 1 },
        tag: JS_TAG_BOOL as i64,
    };

    pub fn tag(&self) -> i32 {
        self.tag as i32
    }

    pub fn is_exception(&self) -> bool { self.tag() == JS_TAG_EXCEPTION }
    pub fn is_object(&self) -> bool { self.tag() == JS_TAG_OBJECT }
    pub fn is_string(&self) -> bool { self.tag() == JS_TAG_STRING }
    pub fn is_number(&self) -> bool {
        let tag = self.tag();
        tag == JS_TAG_INT || tag == JS_TAG_FLOAT64
    }
}

// JS eval flags
pub const JS_EVAL_TYPE_MODULE: c_int = 1;

// JS bytecode deserialization flags
pub const JS_READ_OBJ_BYTECODE: c_int = 1 << 0;
pub const JS_READ_OBJ_ROM_DATA: c_int = 1 << 1;

// JS property flags
pub const JS_GPN_STRING_MASK: c_int = 1 << 0;
pub const JS_GPN_ENUM_ONLY: c_int = 1 << 4;

// Malloc functions struct for custom allocator
#[repr(C)]
pub struct JSMallocFunctions {
    pub js_malloc: Option<unsafe extern "C" fn(s: *mut JSMallocState, size: usize) -> *mut c_void>,
    pub js_free: Option<unsafe extern "C" fn(s: *mut JSMallocState, ptr: *mut c_void)>,
    pub js_realloc:
        Option<unsafe extern "C" fn(s: *mut JSMallocState, ptr: *mut c_void, size: usize) -> *mut c_void>,
    pub js_malloc_usable_size: Option<unsafe extern "C" fn(ptr: *const c_void) -> usize>,
}

#[repr(C)]
pub struct JSMallocState {
    pub malloc_count: usize,
    pub malloc_size: usize,
    pub malloc_limit: usize,
    pub opaque: *mut c_void,
}

#[repr(C)]
pub struct JSPropertyEnum {
    pub is_enumerable: c_int,
    pub atom: u32, // JSAtom
}

// C function type for JS callbacks
pub type JSCFunction =
    unsafe extern "C" fn(ctx: *mut JSContext, this_val: JSValue, argc: c_int, argv: *const JSValue) -> JSValue;

// Class ID type (used for custom JS classes like Timer)
pub type JSClassID = u32;

// Class definition for custom JS classes
#[repr(C)]
pub struct JSClassDef {
    pub class_name: *const c_char,
    pub finalizer: Option<unsafe extern "C" fn(rt: *mut JSRuntime, val: JSValue)>,
    pub gc_mark: Option<unsafe extern "C" fn(rt: *mut JSRuntime, val: JSValue, mark_func: *mut c_void)>,
    pub call: Option<unsafe extern "C" fn(ctx: *mut JSContext, func_obj: JSValue, this_val: JSValue, argc: c_int, argv: *const JSValue, flags: c_int) -> JSValue>,
    pub exotic: *const c_void,
}

extern "C" {
    // Runtime lifecycle
    pub fn JS_NewRuntime() -> *mut JSRuntime;
    pub fn JS_NewRuntime2(
        mf: *const JSMallocFunctions,
        opaque: *mut c_void,
    ) -> *mut JSRuntime;
    pub fn JS_FreeRuntime(rt: *mut JSRuntime);
    pub fn JS_SetMemoryLimit(rt: *mut JSRuntime, limit: usize);
    pub fn JS_SetMaxStackSize(rt: *mut JSRuntime, stack_size: usize);
    pub fn JS_GetRuntime(ctx: *mut JSContext) -> *mut JSRuntime;

    // Context lifecycle
    pub fn JS_NewContext(rt: *mut JSRuntime) -> *mut JSContext;
    pub fn JS_NewContextRaw(rt: *mut JSRuntime) -> *mut JSContext;
    pub fn JS_FreeContext(ctx: *mut JSContext);
    pub fn JS_SetContextOpaque(ctx: *mut JSContext, opaque: *mut c_void);
    pub fn JS_GetContextOpaque(ctx: *mut JSContext) -> *mut c_void;

    // Intrinsics
    pub fn JS_AddIntrinsicBaseObjects(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicDate(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicEval(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicJSON(ctx: *mut JSContext);
    pub fn JS_AddIntrinsicPromise(ctx: *mut JSContext);

    // Global object
    pub fn JS_GetGlobalObject(ctx: *mut JSContext) -> JSValue;

    // Value creation
    pub fn JS_NewObject(ctx: *mut JSContext) -> JSValue;
    #[link_name = "isere_JS_NewString"]
    pub fn JS_NewString(ctx: *mut JSContext, str: *const c_char) -> JSValue;
    // static inline in quickjs.h, shimmed via quickjs_shim.c
    #[link_name = "isere_JS_NewInt32"]
    pub fn JS_NewInt32(ctx: *mut JSContext, val: i32) -> JSValue;
    #[link_name = "isere_JS_NewBool"]
    pub fn JS_NewBool(ctx: *mut JSContext, val: c_int) -> JSValue;
    #[link_name = "isere_JS_NewCFunction"]
    pub fn JS_NewCFunction(
        ctx: *mut JSContext,
        func: JSCFunction,
        name: *const c_char,
        length: c_int,
    ) -> JSValue;

    // Property access
    pub fn JS_SetPropertyStr(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: *const c_char,
        val: JSValue,
    ) -> c_int;
    pub fn JS_GetPropertyStr(ctx: *mut JSContext, this_obj: JSValue, prop: *const c_char) -> JSValue;
    #[link_name = "isere_JS_GetProperty"]
    pub fn JS_GetProperty(ctx: *mut JSContext, this_obj: JSValue, prop: u32) -> JSValue;

    // Value inspection
    pub fn JS_ToInt32(ctx: *mut JSContext, pres: *mut i32, val: JSValue) -> c_int;
    #[link_name = "isere_JS_ToCStringLen"]
    pub fn JS_ToCStringLen(
        ctx: *mut JSContext,
        plen: *mut usize,
        val: JSValue,
    ) -> *const c_char;
    pub fn JS_FreeCString(ctx: *mut JSContext, ptr: *const c_char);

    // Note: JS_IsNumber, JS_IsString, JS_IsObject, JS_IsException are
    // static inline in quickjs.h — use the Rust impl methods on JSValue instead.

    // Memory management (static inline in quickjs.h, shimmed via quickjs_shim.c)
    #[link_name = "isere_JS_FreeValue"]
    pub fn JS_FreeValue(ctx: *mut JSContext, v: JSValue);

    // Evaluation
    pub fn JS_Eval(
        ctx: *mut JSContext,
        input: *const c_char,
        input_len: usize,
        filename: *const c_char,
        eval_flags: c_int,
    ) -> JSValue;

    // JSON
    pub fn JS_ParseJSON(
        ctx: *mut JSContext,
        buf: *const c_char,
        buf_len: usize,
        filename: *const c_char,
    ) -> JSValue;
    pub fn JS_JSONStringify(
        ctx: *mut JSContext,
        obj: JSValue,
        replacer: JSValue,
        space: JSValue,
    ) -> JSValue;

    // Property enumeration
    pub fn JS_GetOwnPropertyNames(
        ctx: *mut JSContext,
        ptab: *mut *mut JSPropertyEnum,
        plen: *mut u32,
        obj: JSValue,
        flags: c_int,
    ) -> c_int;
    #[link_name = "isere_JS_AtomToCString"]
    pub fn JS_AtomToCString(ctx: *mut JSContext, atom: u32) -> *const c_char;
    pub fn JS_FreeAtom(ctx: *mut JSContext, atom: u32);

    // Job execution (promises, async)
    pub fn JS_ExecutePendingJob(rt: *mut JSRuntime, pctx: *mut *mut JSContext) -> c_int;

    // Value duplication — wraps the static inline JS_DupValue via C shim
    // (see c_libs/quickjs_shim.c)
    pub fn isere_JS_DupValue(ctx: *mut JSContext, v: JSValue) -> JSValue;
    pub fn JS_Call(
        ctx: *mut JSContext,
        func_obj: JSValue,
        this_obj: JSValue,
        argc: c_int,
        argv: *const JSValue,
    ) -> JSValue;
    pub fn JS_IsFunction(ctx: *mut JSContext, val: JSValue) -> c_int;
    pub fn JS_ToInt64(ctx: *mut JSContext, pres: *mut i64, val: JSValue) -> c_int;

    // Error throwing
    pub fn JS_ThrowTypeError(ctx: *mut JSContext, fmt: *const c_char, ...) -> JSValue;
    pub fn JS_ThrowInternalError(ctx: *mut JSContext, fmt: *const c_char, ...) -> JSValue;

    // Custom class support (for Timer objects)
    pub fn JS_NewClassID(pclass_id: *mut JSClassID) -> JSClassID;
    pub fn JS_NewClass(rt: *mut JSRuntime, class_id: JSClassID, class_def: *const JSClassDef) -> c_int;
    pub fn JS_NewObjectClass(ctx: *mut JSContext, class_id: c_int) -> JSValue;
    pub fn JS_SetOpaque(obj: JSValue, opaque: *mut c_void);
    pub fn JS_GetOpaque(obj: JSValue, class_id: JSClassID) -> *mut c_void;
    pub fn JS_GetOpaque2(ctx: *mut JSContext, obj: JSValue, class_id: JSClassID) -> *mut c_void;

    // Atom operations (for property deletion)
    pub fn JS_NewAtom(ctx: *mut JSContext, str: *const c_char) -> u32;
    pub fn JS_DeleteProperty(ctx: *mut JSContext, this_obj: JSValue, prop: u32, flags: c_int) -> c_int;

    // Bytecode deserialization
    pub fn JS_ReadObject(
        ctx: *mut JSContext,
        buf: *const u8,
        buf_len: usize,
        flags: c_int,
    ) -> JSValue;
    pub fn JS_EvalFunction(ctx: *mut JSContext, fun_obj: JSValue) -> JSValue;
    pub fn JS_ResolveModule(ctx: *mut JSContext, obj: JSValue) -> c_int;
}

