#ifndef ISERE_CONFIG_H_
#define ISERE_CONFIG_H_

#define ISERE_TCP_MAX_CONNECTIONS                 4

#define ISERE_HTTPD_SERVER_TASK_STACK_SIZE        (1024)
#define ISERE_HTTPD_SERVER_PARSER_TASK_STACK_SIZE (1024 * 4)
#define ISERE_HTTPD_SERVER_POLLER_TASK_STACK_SIZE (1024)

#endif /* ISERE_CONFIG_H_ */
