// Handler code loader.
//
// Embeds pre-compiled QuickJS bytecode at compile time. The bytecode is
// generated from js/handler.js during the build (see CMakeLists.txt).
//
// At runtime, the bytecode is loaded via JS_ReadObject() + JS_EvalFunction(),
// completely skipping the QuickJS parser. This reduces per-request startup
// latency and allows the linker to strip parser code (~30-50KB savings).

/// Pre-compiled handler bytecode, embedded at compile time.
/// Generated by: compile_bytecode (host tool) during the CMake build.
static HANDLER_BYTECODE: &[u8] = include_bytes!("../../js/handler.bin");

/// Get the embedded handler bytecode.
pub fn handler_bytecode() -> &'static [u8] {
    HANDLER_BYTECODE
}
