name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make cmake xxd autoconf

      - uses: actions/checkout@v4
        with:
          repository: cpputest/cpputest
          path: ./cpputest
      
      - name: Install CppUTest from source
        run: autoreconf -i . && ./configure && make tdd
        working-directory: ./cpputest

      - name: Build
        run: mkdir build && cd build && cmake .. && make -j4
        env:
          CPPUTEST_HOME: ${GITHUB_WORKSPACE}/cpputest

      - name: Run unit tests
        run: ./unittests
