name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake libtool cmake

      - name: Build binary
        run: mkdir build && cd build && cmake .. && make -j
