name: Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build dependencies
        run: make -j quickjs

      - name: Build test executable
        run: make -j tests

      - name: Run tests
        run: ./test
