name: Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake libtool ninja

      - name: Build dependencies
        run: make -j deps

      - name: Build test executable
        run: make -j unittest

      - name: Run tests
        run: ./unittest -v
